services:
    auth-service:
        build: .
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - PORT=3000
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - loki

    redis:
        image: redis:7-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        command: redis-server --appendonly yes
    redis-ui:
        image: rediscommander/redis-commander:latest
        ports:
            - '8081:8081'
        environment:
            - REDIS_HOSTS=local:redis:6379
        depends_on:
            - redis

    prometheus:
        image: prom/prometheus:latest
        ports:
            - '9090:9090'
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'

    grafana:
        image: grafana/grafana:latest
        ports:
            - '3002:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana-storage:/var/lib/grafana

    loki:
        image: grafana/loki:latest
        ports:
            - '3100:3100'
        volumes:
            - ./monitoring/loki.yml:/etc/loki/local-config.yaml
        command: -config.file=/etc/loki/local-config.yaml

    promtail:
        image: grafana/promtail:latest
        volumes:
            - ./logs:/var/log
            - ./monitoring/promtail.yml:/etc/promtail/config.yml
        command: -config.file=/etc/promtail/config.yml

volumes:
    grafana-storage:
    redis-data:
