global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:3000"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
